language: node_js
node_js:
- 6.10.3
services:
- docker
notifications:
  email:
  - relfishere@gmail.com
  - okanvurdu@gmail.com
  - frknbasaran@gmail.com
script:
- cd src
- docker build -t api .
- docker tag api:latest $DOCKER_HUB_USERNAME/api:prod
- docker push $DOCKER_HUB_USERNAME/api:prod
env:
  - SOZLUK_ENV=test
  global:
  - secure: S3oo05Z2lpVOa4/4Y8UIhT/CvimTgVU2TArnpTCtXzwixviYCrjcLqux1XlqidhbpaDD2UGY0aIhMN0HO3W8HK2val+FriSgS1BbpOPCvYUgXPrRe6wV0b/O6nN+iLprA7ZLs71s/99a21IdyUQFWH9DI991zDuXkl6kBEHwrzV2ELJgcxKnW4sSV9J0b/Cr6gKLTUhOdA9TpKFABpWmUdpOQd+w9Bdk/tdyasMqHVwq1SNp6dzzlmw/hT2wy2oeOsozyZp1dChrXDUShpluQCHlFCIXEi1gDs15xAXQ6D+/CVE8RXXgyakewbWZ+U3KLOY4kX5RVxjY2PDsR5R4pe3Ip2tssvGcfaUlPtLgLncTAfOZea8e2Ub21aCcok5uWnRXzijHsfOKdwTC7/3im6j/kqJYOfSWXkdiGbBow6I6Rn/ByuuwuV6bLk3yMtawJBTLuJXAkN60JCtVAo+5ZFW56pGX97xSs6C41Xl0v8hNwku1y5cexSY2cONnh49+inyCKRqH05mL6iX2zNmwKHKzR1DLrBbX/NJ4Iro8plC0zH/AmAjYkRaHRkXLCNkZMCP5n60qUvQVlMe5D+ZhTOnl4oOAwFYqec+yL/3GVU4Z8JyxFlR8rDYtTbmapR2YM1+kC7YoApvBVcjlglLgXxT1eUXOrgXnxsdBEVLngxc=
  - secure: Yz1GWr2VnNJYOjD7ebSGTRgwhQwee9ti9ucmcdQDx3awpUizlwkg/36HwoZrrLfGdvCJ7SLcc7DYh6+sRnpK4FTez/QyOB8/g+ljsdSdZ7St6bXQU8ryWmU7295iXiRf5VWU139X3itb49rBxLXCwdZhMCEMy0c4aqVa7sUpEsLQUFVBQ7T/aCLDaAZ3cOwCd/S6XkPycgn6k/Nk/Anbksxe/5dm4NB8X1OfTr9RYFWK+ZyG4ZwByyK0guv5RaiJFR+Oba46w/nKnAcR0mQrEdGTAHTe62MdjP/BPwiet9P+cRL2YxfPc8ymtYtEuoCHbIf7KkdsrK/D5NwEbAzmR5I0poozeIVCuksF9XkRVz7cOqTmrKYfr9fnjrhK/eM0fSZlhQfVP6JQKF/AnNhS25J24oP/RwTmeZtdnlQKiv0vhcozn9wcvwMmAaAn4psDllkFY5tZ1ZsbwP2HnGA4W6g3QiD1eMkxmF+Qprat5X2sdtOH2xGKbdxWpVNQhdso+6c3A90Lsgu4e4lWZ7i19nlnEFyDc+e3fT/T4y23/QPR9KAAxWOTwlDfrFEPVraruMIS7xJqPq4Uh4ZftPh3HBhMoFpl0Af2QAAQAetz4rPG1SnKjHaq563UGVwlsBYv55Nl7wLt5gGQAqWjka1a8kvsdZCZIlEWE2tY656skNs=
  - secure: Bwm44nPi4pK1iAKy9Vx2AccT+/9CQblREGoXFd5fdSf66nmK/DxxbFdBE/t39alW9/G8NHSnNAefxuzXzu8qIlGMzccsAtZFX0WptKz6K74ItD6GnR6V8BiL2BvKF8R/9+s2lvcqmSYlNjdw+7PZyT9rDGcgE8BGCCJY9r/e1VP/aKPwN87zwctZKClvvL+pWOc4a0d4N0GVq7mf2ZrRbO+AYHPiN1JfNlUKHV26Mgga21ohe+iZUWx67DczJcfZZnbXRQvzuVzLVPPkKJNyZ1osO0yLZEoim7EkgJf0x3CCRRg93WfG8fzTaijOlAloma6BYifId3K17SdOPX6iFkDdFEjaDdfLf1WJUOzY22WxrGMgMZmlAVLiAzUhD7AMiPTVnMsqbcaL0/GU72CC4NHUshiGN1m6ZU+XFl3ErEaY0r1PONURt+jx+//PW4Qw5WDtF29JzL//8pb80O8MTH09WsxwMpBD37HA+0Hsc4Ptdn+GYpbxsv+wiInzC4+W6qb/CbTWSrhbh4CeEYdo69Yuj4vXy9CbethfkE/vgDLRy7noPZ+DzajYjPXfWVGlrWvQxOyHubIIFcOWu+FcP5aCubxLVN3z52URMLUCURGesKvlX+XDAwj+L8nJoJuFmW0XQo/SCm2vzweltgg7bSm/pB891azKsJ0cgrS29zQ=
  - secure: jXot3cIsixAaL6e3uNFNXq8nSrQBFFC9XV9G1eP4n/qeIKsyifYn5cCA+8eY1S+NfaqrvUT0/fw0/jotkECVBBTJwe+jjiiql8rY0xEVrmLcH6HUftI2AcJmsM1mroQNC5jobOr0mASe8y4/AcAeDSGX9t8RKbQlvdGm2LxGWj3CwrGjkiKh+WCyFPGoQ9QC4mFGnq8UIhzSunJDPt7ZVBhrhcASt8mI8hrw/uUclhV74nN9pJLs++RlpdXkk+oo4Rq44VM5Rlk1iG0VSnVZKC3bYK1JCgdhizDdfE2IZtVWTIu3ISOMdyfWIu2Yh+Xj5HVg5tyjtkwSXo42EE7NvCnwEpLBwxU5ZhT6VwYvtu6HWrUo2iAiDwdJwVkVuhltGl/A7jezJPOHpTDEnMl/xdXlQoBjSQXPvGLWfbtrQHC/tZ51tXWis4zyoReAgCiigWypBXvTxiIgjE9ikQYOKyPG6qJEkBDXL878cTUdF+xuHFpquvkOCaStK0lYbwEL/pLZ9BuInetAsk2UF5eqJEcGJ5fnaCGfuia4yFRhorW9weQSw0tnWirlK3xd6OvS37F8/CNAVIFJlU7EC3DneaEUNbdglTnkkzTxEYn7Vpeq0lqHAC314q+GCVSRcX/zgfk8A83t+rCcntKKcwJ0jydhKNDUzSXYfg3L2gQHNSs=
before_install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_4f35dbab3554_key -iv $encrypted_4f35dbab3554_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker build --build-arg SOZLUK_DB_URI=$SOZLUK_DB_URI -t apitest .
after_script:
- docker rm -f app
deploy:
  provider: script
  skip_cleanup: true
  script: cd .. && chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key
    ubuntu@ec2-35-157-80-0.eu-central-1.compute.amazonaws.com "./deploy.sh"
  on:
    branch: master
